package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dryseed.dryseedapp.practice.localMusic.MusicDB;
import com.dryseed.dryseedapp.practice.localMusic.UserMusicDB;

import greendao.MusicDBDao;
import greendao.UserMusicDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicDBDaoConfig;
    private final DaoConfig userMusicDBDaoConfig;

    private final MusicDBDao musicDBDao;
    private final UserMusicDBDao userMusicDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicDBDaoConfig = daoConfigMap.get(MusicDBDao.class).clone();
        musicDBDaoConfig.initIdentityScope(type);

        userMusicDBDaoConfig = daoConfigMap.get(UserMusicDBDao.class).clone();
        userMusicDBDaoConfig.initIdentityScope(type);

        musicDBDao = new MusicDBDao(musicDBDaoConfig, this);
        userMusicDBDao = new UserMusicDBDao(userMusicDBDaoConfig, this);

        registerDao(MusicDB.class, musicDBDao);
        registerDao(UserMusicDB.class, userMusicDBDao);
    }
    
    public void clear() {
        musicDBDaoConfig.clearIdentityScope();
        userMusicDBDaoConfig.clearIdentityScope();
    }

    public MusicDBDao getMusicDBDao() {
        return musicDBDao;
    }

    public UserMusicDBDao getUserMusicDBDao() {
        return userMusicDBDao;
    }

}
