package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dryseed.dryseedapp.practice.localMusic.MusicDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MUSIC_DB".
*/
public class MusicDBDao extends AbstractDao<MusicDB, Long> {

    public static final String TABLENAME = "MUSIC_DB";

    /**
     * Properties of entity MusicDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Artist = new Property(2, String.class, "artist", false, "ARTIST");
        public final static Property Duration = new Property(3, int.class, "duration", false, "DURATION");
        public final static Property Size = new Property(4, int.class, "size", false, "SIZE");
        public final static Property Back = new Property(5, int.class, "back", false, "BACK");
    }


    public MusicDBDao(DaoConfig config) {
        super(config);
    }
    
    public MusicDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MUSIC_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ARTIST\" TEXT," + // 2: artist
                "\"DURATION\" INTEGER NOT NULL ," + // 3: duration
                "\"SIZE\" INTEGER NOT NULL ," + // 4: size
                "\"BACK\" INTEGER NOT NULL );"); // 5: back
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MUSIC_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MusicDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String artist = entity.getArtist();
        if (artist != null) {
            stmt.bindString(3, artist);
        }
        stmt.bindLong(4, entity.getDuration());
        stmt.bindLong(5, entity.getSize());
        stmt.bindLong(6, entity.getBack());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MusicDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String artist = entity.getArtist();
        if (artist != null) {
            stmt.bindString(3, artist);
        }
        stmt.bindLong(4, entity.getDuration());
        stmt.bindLong(5, entity.getSize());
        stmt.bindLong(6, entity.getBack());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MusicDB readEntity(Cursor cursor, int offset) {
        MusicDB entity = new MusicDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // artist
            cursor.getInt(offset + 3), // duration
            cursor.getInt(offset + 4), // size
            cursor.getInt(offset + 5) // back
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MusicDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setArtist(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDuration(cursor.getInt(offset + 3));
        entity.setSize(cursor.getInt(offset + 4));
        entity.setBack(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MusicDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MusicDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MusicDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
